export const TILES_CATALOG = [
  { name: "بلانيوم سكني (Planum)", origin: "إسبانيا", count: 11, family: "terracotta" as const, colorHex: "#d4784e", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/terracotta-seamless.png" },
  { name: "بلانيوم أسود (Planum)", origin: "إسبانيا", count: 11, family: "dark" as const, colorHex: "#5a5a5a", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/dark-seamless.png" },
  { name: "بلاك ستون (Planum)", origin: "إسبانيا", count: 11, family: "dark" as const, colorHex: "#4a4a4a", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/dark-seamless.png" },
  { name: "بلانيوم بني (Planum)", origin: "إسبانيا", count: 11, family: "brown" as const, colorHex: "#8b5e3c", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/brown-seamless.png" },
  { name: "بلانوم أحمر (Planum)", origin: "إسبانيا", count: 11, family: "terracotta" as const, colorHex: "#c46040", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/terracotta-seamless.png" },
  { name: "فيسيوم 3 رمادي (Visum3 Gray)", origin: "إسبانيا", count: 11.5, family: "dark" as const, colorHex: "#6a6a6a", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/dark-seamless.png" },
  { name: "فيسيوم بني غامق (Visum3 Rustic)", origin: "إسبانيا", count: 11.5, family: "brown" as const, colorHex: "#7a4e2c", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/brown-seamless.png" },
  { name: "بلانا أسود (LOGICA Plana)", origin: "إسبانيا", count: 11, family: "dark" as const, colorHex: "#3a3a3a", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/dark-seamless.png" },
  { name: "بلانا ايموشن (LOGICA Emotion)", origin: "إسبانيا", count: 11, family: "modern" as const, colorHex: "#9e8e7e", width: 0.28, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/modern-seamless.png" },
  { name: "فلات (Flat Natural / Red)", origin: "إسبانيا", count: 10.7, family: "terracotta" as const, colorHex: "#d4784e", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/terracotta-seamless.png" },
  { name: "إنوفا (Innova)", origin: "إسبانيا", count: 11.5, family: "modern" as const, colorHex: "#a89484", width: 0.28, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/modern-seamless.png" },
  { name: "فيينا (Vienna)", origin: "إسبانيا", count: 11.5, family: "modern" as const, colorHex: "#b09888", width: 0.28, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/modern-seamless.png" },
  { name: "فيرتوس كلينكر (Virtus Klinker)", origin: "BMI", count: 11.5, family: "modern" as const, colorHex: "#8a7a6a", width: 0.28, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/klinker-seamless.png" },
  { name: "سيبرانو (CEPRANO)", origin: "BMI", count: 14.5, family: "special" as const, colorHex: "#7a6a5a", width: 0.27, length: 0.46, type: "ceramic" as const, textureUrl: "/textures/tiles/klinker-seamless.png" },
  { name: "إم جي بلس (+MG)", origin: "BMI", count: 11, family: "modern" as const, colorHex: "#9a8a7a", width: 0.28, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/modern-seamless.png" },
  { name: "فاريو 5 (Vario 5)", origin: "BMI", count: 14, family: "modern" as const, colorHex: "#8e7e6e", width: 0.28, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/modern-seamless.png" },
  { name: "مارسيليا أيديال", origin: "اليونان", count: 11, family: "terracotta" as const, colorHex: "#da8054", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/terracotta-seamless.png" },
  { name: "المنحني وتوسال (CURVED)", origin: "إسبانيا", count: 10.5, family: "curved" as const, colorHex: "#c47040", width: 0.27, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/curved-seamless.png" },
  { name: "ميجمو (Maigmo)", origin: "إسبانيا", count: 10.5, family: "curved" as const, colorHex: "#be6838", width: 0.27, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/curved-seamless.png" },
  { name: "لوسا لوجيكا (Lusa Logica)", origin: "BMI", count: 12, family: "modern" as const, colorHex: "#928270", width: 0.28, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/modern-seamless.png" },
  { name: "كوبرت كلينكر (Cobert)", origin: "BMI", count: 12.5, family: "curved" as const, colorHex: "#b86030", width: 0.27, length: 0.48, type: "ceramic" as const, textureUrl: "/textures/tiles/curved-seamless.png" },
  { name: "تيراكوتا (Terracotta)", origin: "إيطاليا", count: 14, family: "terracotta" as const, colorHex: "#d07048", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/terracotta-seamless.png" },
  { name: "كلاسيك / نيوكلاسيك", origin: "إيطاليا", count: 14, family: "brown" as const, colorHex: "#7a5030", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/brown-seamless.png" },
  { name: "بورتوغيز (PORTOGHESE)", origin: "إيطاليا", count: 14, family: "terracotta" as const, colorHex: "#cc6c44", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/terracotta-seamless.png" },
  { name: "أمازونيا (Amazonia)", origin: "البرازيل", count: 12, family: "terracotta" as const, colorHex: "#c86a42", width: 0.29, length: 0.47, type: "ceramic" as const, textureUrl: "/textures/tiles/terracotta-seamless.png" },
];

export const MARKET_LENGTHS = [3.0, 3.3, 3.6, 3.9, 4.2, 4.8, 5.1, 5.4, 5.7, 6.0];
